@startuml
activate Node_N
Node_0 -> Node_N: <request_t> **NODE_CONNECTION**
Node_N -> Node_0: <integer> BLOCKCHAIN_SIZE_N
Node_0 -> Node_N: <integer> BLOCKCHAIN_SIZE_0
Node_0 <-- Node_N: <block_t> Block #1
Node_0 <-- Node_N: <block_t> Block #N
deactivate Node_N
Node_0 --> Node_X: <block_t> Block #X
Node_0 --> Wallet_X: <trns_t> Transaction (Block #X)

@enduml
