@startuml
hnote over Wallet: new transaction
Wallet -> Nodo: <request_t> TRANSACTION
Wallet->Nodo: <trns_t> transaction
Wallet<-Nodo: <integer> confirma
activate Nodo
hnote over Nodo: ** add ** in blockchain
hnote over Nodo: ** flooding **

@enduml
