@startuml
PeerX --> Peer:richiesta di invio blocco
hnote over Peer: ricezione blocco
alt blocco arrivato non è da eliminare
  alt blocco non è nella mia blockchain
    alt seq del blocco successivo all'attuale
     alt se ho una multicoda
      hnote over Peer: salvo i blocchi
      hnote over Peer: flooding di tali blocchi
     end
    end
    hnote over Peer: aggiungo alla blockchain
    hnote over Peer: flooding
  end
else da eliminare
  
end
@enduml
